CONFIG_LIBAV="\
	--disable-bzlib \
	--disable-muxers \
	--disable-bsfs \
	--disable-avdevice \
	--disable-devices \
	--disable-encoders \
	--enable-muxer=spdif \
	--enable-protocols \
	--enable-demuxers \
	--enable-parsers \
	--enable-decoders \
    --enable-libdav1d --enable-libopus"
