/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4.5-17-g9d1b4311a1-Kodi"
#endif /* AVUTIL_FFVERSION_H */
